// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nucleus.Infrastructure.Data;

#nullable disable

namespace Nucleus.Infrastructure.Migrations
{
    [DbContext(typeof(NucleusDbContext))]
    [Migration("20260720000001_AddTrialEndsAt")]
    partial class AddTrialEndsAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal snapshot — only the attributes above matter for migration discovery.
            // EF Core uses [DbContext] and [Migration] to register this migration.
        }
    }
}
